### ISSUE TITLE
Add comment section to Quotes and Poems page

### ISSUE THREAD

**Issue by jfehrenbacher** [suwebdev/sparkling-art#11]
Authored by: Jack

URL of the user story: https://github.com/suwebdev/sparkling-art/wiki/User-Stories:-Poems-and-Quotes)

Size of the user story: 2

Your reasoning for adding this Issue to the Sprint: Adding the basic functionality now will allow us to work out logistic and stylistic kinks later, and it should be relatively simple.

What is the priority that has been assigned?: Not high priority, but worth getting out of thew ay.

How do you interpret this fitting into the process of building the project? : I believe that adding a comment section won't affect the rest of the project unless we end up wanting to create a more complex system than simply having a comment section at the bottom of the quotes and poems pages. In the initial user story I claimed that we wanted people to be able to comment on each and every quote or poem, but in retrospect that may be a bit much. We can talk about it more, as it's certainly possible.

Why should this be in the Sprint this time? Why not wait until the next Sprint?: Beginning to work with it now can point us in different directions. For example, currently I'm struggling to get the EasyComment plugin to work (http://www.jswidget.com/lab/easy-comment.html) so I'm settling for this comment box from HTMLCommentBox.com (http://www.htmlcommentbox.com/). It may not have all of the functionality that I stated was necessary previously, but we may not even need all of the features stated. If we add this now, in this sprint, we can have a better informed discussion about our needs surrounding commenting on our website.

**Comment by crossm2** [comment]
Closing out issue. Reviewed pull request with active quotes links and merged changes to the master.
