### ISSUE TITLE
RDF Poetry Site Logo

### ISSUE THREAD

**Issue by crossm2** [suwebdev/sparkling-art#8]
Authored by: Marlie
URL of the requirements/User Story: https://github.com/suwebdev/sparkling-art/wiki/User-Story:-View-Public-Website
Size of the Requirement/User Story: 1
Your reasoning for adding this Issue to the Sprint: It is important that users can identify what site they have landed on when they come to our page. A logo and clearly defined site title will fulfill this requirement. (Criteria 3 on this user story)
What is the priority that has been assigned?: Priority 1 because users will need to know what page they have landed on in order to enjoy/discover the offerings. 
How do you interpret this fitting into the process of building the project? : This is a foundation piece to getting any web page started. It can be edited at any time, but provides a good navigational starting point.
Why should this be in the Sprint this time? Why not wait until the next Sprint?: This will provide a good starting place for additional navigational items and/or theme and styling components.

**Comment by ThomasKDesign** [comment]
A must-have feature on every site for sure! Nice work Marlie!
